### ISSUE TITLE
data_gen.ipynb has issues

### ISSUE THREAD

**Issue by pjuangph** [Rose-STL-Lab/Approximately-Equivariant-Nets#1]
Issue 1: phiflow undefined. 
You need to change import to this
```python
from PhiFlow import *
```

Issue #2: NameError: name 'StaggeredGrid' is not defined
I have no idea what this is. Can you give the notebook a try? thanks

**Comment by Rui1521** [comment]
I'm so sorry for not getting back to you sooner. I didn't see your comment. Did you install the correct version of PhiFlow? We just updated the code, would you mind trying again?
